name: Linux CI

on: [push, pull_request]

jobs:
  Linux:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: python -m pip install meson==1.4.0 ninja

    - name: Install Ubuntu dependencies
      run: sudo apt install -y libimgui-dev libsdl2-dev

    - name: Configure project
      run: |
        meson setup build

    - name: Build and test
      run: |
        meson test -C build/ -v

    - name: Upload Test Log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Meson_Testlog
        path: builddir/meson-logs/testlog.txt
